### ISSUE TITLE
Cannot delete problems of "0sec CPU" and "0MB Memory"

### ISSUE THREAD

**Issue by hakatashi** [hiromu/arrow-judge-web#1]
When I accidently added problems assigned "0sec CPU" and "0MB Memory" to judge.npca.jp with problem ID #199, I was not able to delete the problem. I changed assignment of CPU and memory to 1sec and 10MB, and the problem has gone. Also the similar situation was observed few times...

**Comment by hiromu** [comment]
I regret to inform you that I no longer have the administrative privilege of `npca.jp`. Thus, it is now difficult to replicate and resolve this issue. Please let me close the Issue.
